### PR TITLE
Add capabilities to run optimally scheduled network via WNTR as a check

### PR DESCRIPTION
**Pull request by enzoliuyang94**
Modify the WNTR object that saves the configuration of the network, enforce the initial conditions and controls solved by WaterModels.jl. The simulation is a fidelity-check of the WaterModels.jl package.

### CODE REVIEW

**Comment by jjstickel** [comment]
@enzoliuyang94 , we need to check that all this still works with Byron's refactor that split out the valves from the pipes. I asked him to provide a new solution file.

**Comment by jjstickel** [comment]
@enzoliuyang94 , the latest data structures in WaterModels.jl#master has changed, specifically for valves. Can you get this branch working with master before we merge it? Hopefully it is not too hard. I think in `simulation.jl` references to `check_valves` and `shutoff_valves` need to be changed to just `valve`. To know whether a valve is a check valve or shutoff valve, you can use the `flow_direction` field.

**Comment by enzoliuyang94** [comment]
> @enzoliuyang94 , the latest data structures in WaterModels.jl#master has changed, specifically for valves. Can you get this branch working with master before we merge it? Hopefully it is not too hard. I think in `simulation.jl` references to `check_valves` and `shutoff_valves` need to be changed to just `valve`. To know whether a valve is a check valve or shutoff valve, you can use the `flow_direction` field.

Ok, no problem. Was the jSON file Byron sent yesterday generated by his latest WaterModels.jl?

**Comment by jjstickel** [comment]
> Ok, no problem. Was the jSON file Byron sent yesterday generated by his latest WaterModels.jl?

No, and there is in fact a problem with indexes not matching up. Byron should merge shortly (today?) the branch that he used to generate that solution. @tasseff, please comment here when you do the merge. Thanks!

**Comment by tasseff** [comment]
@enzoliuyang94, @jjstickel, just merged the recent changes to master. Thanks!

**Comment by enzoliuyang94** [comment]
> @enzoliuyang94, @jjstickel, just merged the recent changes to master. Thanks!

@tasseff Thanks! Was the jSON you sent me formatted the same way as in the latest WaterModels.jl? If not, could you send me a new jSON file?

**Comment by jjstickel** [comment]
The new JSON file seems to be of a similar format as the previous one. I tried it with your previous script, and it read in just fine. Running WMA.simulate() has trouble, though, because of the changed valve designation as I pointed above.

**Comment by enzoliuyang94** [comment]
> The new JSON file seems to be of a similar format as the previous one. I tried it with your previous script, and it read in just fine. Running WMA.simulate() has trouble, though, because of the changed valve designation as I pointed above.

@jjstickel Ok, then I will work on this and test with the jSON file Byron sent on Monday. Thanks.

**Comment by jjstickel** [comment]
Thanks @enzoliuyang94 . I'll merge, and you can continue to develop the next features by opening a new branch, although I suggest more descriptive branch names.

**Pull request merged**
