### PR TITLE
Modularize simulation setup, control update, and execution code

### PR DESCRIPTION
**Pull request by tasseff**
This is intended to separate the functionality implemented in #31. There, the simulation routine sets up the WNTR network, updates the controls, and simulates the network in a single function. Here, one function sets up the network (for later reuse), another function sets the controls on the network given a WaterModels solution, and another function simulates the network. This new modularization allows us to avoid the overhead associated with setting up a new network and updating controls, which is likely important when simulating the same network repeatedly an iterative algorithm.

This also essentially acts as a review of #31. The primary differences from that implementation are: (1) the `status` keyword in the WaterModels data object is not the same as a WNTR `status` keyword, and that has been corrected here; and (2) hydraulic settings are initialized for WNTR in case we want to simulate other head loss types. Otherwise, (I think) this mimics the functionality in that pull request.

### CODE REVIEW

**Comment by tasseff** [comment]
I'm encountering some EPANET 200 errors while using this... Not totally ready for a pull, yet, so I will revert to draft for the time being.

**Comment by enzoliuyang94** [comment]
> I'm encountering some EPANET 200 errors while using this... Not totally ready for a pull, yet, so I will revert to draft for the time being.

@tasseff Was it because of the settings on hydraulic options?

**Comment by tasseff** [comment]
In this case, it seems to be related to the setting of valve statuses from WaterModels solutions... I imagine this is a numerical issue associated with those solutions. Any tips?

**Comment by tasseff** [comment]
@enzoliuyang94 I noticed that something in your code resolves this issue, but I'm not sure why it is being done. When adding valve controls, you only add them if the valve satisfies this condition: `if data["nw"]["1"]["valve"][i]["source_id"][1] != "valve"`. Why aren't controls added for all valves? It seems like they're being selectively added based on this condition.

**Comment by enzoliuyang94** [comment]
> In this case, it seems to be related to the setting of valve statuses from WaterModels solutions... I imagine this is a numerical issue associated with those solutions. Any tips?

@tasseff Controls are not added to all valves because check valves don't need controls. Because check valves' source_id points to pipes, I use that condition to check whether a valve is a check valve or a shutoff valve. I only add controls to shutoff valves associated with tanks.

**Comment by tasseff** [comment]
@enzoliuyang94 Shutoff valves can also point to a `source_id` of `pipe`, though. All valves connected directly to tanks are shutoff valves, but not all shutoff valves have to be connected to tanks. How do you propose we handle this? This indeed seems to be the cause of the error (i.e., setting of statuses not associated with a `source_id` of `valve`). I don't understand why setting a check valve's status would result in this error.

**Comment by enzoliuyang94** [comment]
> @enzoliuyang94 Shutoff valves can also point to a `source_id` of `pipe`, though. All valves connected directly to tanks are shutoff valves, but not all shutoff valves have to be connected to tanks. How do you propose we handle this? This indeed seems to be the cause of the error (i.e., setting of statuses not associated with a `source_id` of `valve`). I don't understand why setting a check valve's status would result in this error.

@tasseff When I check valve status through "wm_data["nw"]["1"]["valve"][valve_id]["source_id"][1]", those that are shutoff valves do return 'valve', not pipe. I just check this again. For check valves, they are truly passive components that shouldn't be controlled, it appears that EPANET is enforcing this in some way according to what you describe.

**Comment by tasseff** [comment]
@enzoliuyang94 You're looking at a specific network instance where this property happens to hold. In the general case, not all shutoff valves have to be connected to tanks. There is a translation process in WaterModels that will convert a pipe with a shutoff valve to a pipe *and* a shutoff valve. This is a separate procedure from adding shutoff valves to tanks and their auxiliary nodes.

From what you're saying, it sounds like the valve status should be set based on the directionality of a WaterModels valve (e.g., "POSITIVE," "UNKNOWN"), which differentiates a check valve from a shutoff valve. Still, it is a bit bothersome that the setting of a check valve's status in WNTR would result in an EPANET error.

**Comment by enzoliuyang94** [comment]
> @enzoliuyang94 You're looking at a specific network instance where this property happens to hold. In the general case, not all shutoff valves have to be connected to tanks. There is a translation process in WaterModels that will convert a pipe with a shutoff valve to a pipe _and_ a shutoff valve. This is a separate procedure from adding shutoff valves to tanks and their auxiliary nodes.
> 
> From what you're saying, it sounds like the valve status should be set based on the directionality of a WaterModels valve (e.g., "POSITIVE," "UNKNOWN"), which will allow us to differentiate between setting a check valve (which we should not do, apparently) and a shutoff valve. Still, it is a bit bothersome that the setting of a check valve's status in WNTR would result in an EPANET error.

@tasseff I see, that makes sense. I will change the identification process as you suggested. Thanks.

**Comment by tasseff** [comment]
@enzoliuyang94 Do you want to review and work off of this branch? I think I've addressed it correctly in my most recent commit.

**Comment by jjstickel** [comment]
So we have a PR against a branch that also has PR open against master... I reviewed @enzoliuyang94's PR, and as far as I can tell, this looks like a good way to make the code modular, which I agree is a good idea. Other than that, I will defer review to @enzoliuyang94 .

**Review by jjstickel — APPROVED** [review]
So we have a PR against a branch that also has PR open against master... I reviewed @enzoliuyang94's PR, and as far as I can tell, this looks like a good way to make the code modular, which I agree is a good idea. Other than that, I will defer review to @enzoliuyang94 .

**Comment by jjstickel** [comment]
@enzoliuyang94 , does this look good to you? If it looks mostly OK, I suggest merging it---it will merge into your other branch. Then you can test the functions once more in that branch before merging into master.

**Review by enzoliuyang94 — APPROVED** [review]

**Comment by enzoliuyang94** [comment]
> @enzoliuyang94 , does this look good to you? If it looks mostly OK, I suggest merging it---it will merge into your other branch. Then you can test the functions once more in that branch before merging into master.

Yes, this looks good to me.

**Pull request merged**
